name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test And Coverage
    runs-on: ubuntu-latest
    env:
      MIN_COVERAGE: "70.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...
